export const benefState = {
  benefType: "",
  availableBenefs: [
    {
      name: "kim",
      email: "kim@email.anycom",
      benefPhone: "+263468468648167",
      country: "zw",
      state: "",
      city: "shurugwi",
      address: "x city, Y state, Z Country abc street, z block",
      bank: "bankA",
      bankBranch: "branch xyz",
      bankAcc: "4864518464",
      mobileOperator: "mtn",
      wallet: "usd",
      walletNumber: "4654841631",
      agent: "kebab",
      agentLocation: "",
      agentMobile: "",
    },
    {
      name: "sample",
      email: "sample@email.anycom",
      benefPhone: "+263468468648167",
      country: "zw",
      state: "",
      city: "shurugwi",
      address: "zsample x city, Y state, Z Country abc street, z block",
      bank: "",
      bankBranch: "",
      bankAcc: "",
      mobileOperator: "",
      wallet: "",
      walletNumber: "",
      agent: "kebab",
      agentLocation: "",
      agentMobile: "",
    },
  ],
  selectedBenef: {
    name: "kim",
    email: "kim@email.anycom",
    benefPhone: "+263468468648167",
    country: "zw",
    state: "",
    city: "shurugwi",
    address: "x city, Y state, Z Country abc street, z block",
    bank: "",
    bankBranch: "",
    bankAcc: "",
    mobileOperator: "",
    wallet: "",
    walletNumber: "",
    agent: "kebab",
    agentLocation: "",
    agentMobile: "",
  },
  newBenef: {
    name: "",
    email: "",
    benefPhone: "",
    country: "",
    state: "",
    city: "",
    address: "",
    bank: "",
    bankBranch: "",
    bankAcc: "",
    mobileOperator: "",
    wallet: "",
    walletNumber: "",
    agent: "kebab",
    agentLocation: "",
    agentMobile: "+263779500500",
  },
};
